Youtube video
Hecktors/rueda-de-casino pull request #12
Opened 2020-11-26 11:36 UTC by Hecktors

2020-11-26 12:15 UTC, mariothomsen requested changes

2020-11-26 12:15 UTC, mariothomsen commented on src/pages/Session.js
> +            <div />
Empty Divs?

2020-11-26 12:15 UTC, mariothomsen commented on src/components/MoveList.md
> +import moves from '../data/mock.json'
The name mock.json is difficult to understand. Would prefer moves.json.

2020-11-26 12:15 UTC, mariothomsen commented on src/assets/img/youtube.svg
> +   xmlns:dc="http://purl.org/dc/elements/1.1/"
Seems to be a huge file. Maybe there is some unnecessary code?

2020-11-26 13:23 UTC, lmachens reviewed
gj

2020-11-26 13:23 UTC, lmachens commented on src/assets/img/youtube.svg
> +   xmlns:dc="http://purl.org/dc/elements/1.1/"
There are some not used properties in your SVGs. These properties are created by design tools like Adobe XD.
For example, you can remove id and data-name.
Take a look at https://www.svgminify.com/

Similar to Hanttone/capstone-project#8 (comment)

2020-11-26 13:23 UTC, lmachens commented on src/components/MoveList.js
> +        onClick={() => openVideo(video_id, video_start)}
You could could directly use `setVideo`  and remove `openVideo`

```suggestion
        onClick={() => setVideo(video_id, video_start)}
```

2020-11-26 13:23 UTC, lmachens commented on src/components/MoveList.js
> +  const listItems = moves.map(({ name, id, video_id, video_start }) => (
It looks not so clean if you mix different naming conventions. You have underscores here and use camelCase for other variables.
I would update your pensum.json to avoid different conventions.

2020-11-26 13:23 UTC, lmachens commented on src/components/Video.js
> +    ></iframe>
```suggestion
    />
```

2020-11-26 13:23 UTC, lmachens commented on src/lib/localStorage.js
> +    console.error(error)
Consider using a default value here. 
In an error case, the user won't usually notice because dev tools are not opened.
`getLocalStorage` returns `undefined` which might lead to other issues.

2020-11-26 15:18 UTC, Hecktors commented on src/pages/Session.js
> +            <div />
Just kind of placeholder to make my layout work.

2020-11-26 15:18 UTC, Hecktors commented on src/components/MoveList.md
> +import moves from '../data/mock.json'
I see

2020-11-26 15:18 UTC, Hecktors commented on src/assets/img/youtube.svg
> +   xmlns:dc="http://purl.org/dc/elements/1.1/"
Thanks for the hint!

2020-11-27 11:03 UTC, Hecktors commented on src/components/MoveList.js
> +        onClick={() => openVideo(video_id, video_start)}
Yeah... why not?. Guess I'll it this way

2020-11-27 11:34 UTC, Hecktors commented on src/components/MoveList.js
> +  const listItems = moves.map(({ name, id, video_id, video_start }) => (
Right

2020-11-27 15:22 UTC, Hecktors commented on src/components/Video.js
> +    ></iframe>
Right again

2020-11-27 15:27 UTC, merged