Play song
Hecktors/rueda-de-casino pull request #5
Opened 2020-11-18 16:22 UTC by Hecktors

Please review the first vision of my awesome app. Thanks for your feedback!

2020-11-18 18:34 UTC, JulianBlohm reviewed
The logic and functionality is nice! Great work ✨ 
Found some stuff you should consider to improve or refactor in reason of readability.

2020-11-18 18:34 UTC, JulianBlohm commented on src/App.js
> +  background-color: var(--primery-color);
```suggestion
  background-color: var(--primary-color);
```
little typo in primary :)

2020-11-18 18:34 UTC, JulianBlohm commented on src/components/Header.js
> +      ? 'var(--default-heder-color)'
```suggestion
      ? 'var(--default-header-color)'
```
 Shouldn't work like that if the color variable is written wrong 🎨

2020-11-18 18:34 UTC, JulianBlohm commented on src/components/Header.js
> +
Nice logic! Consider to use switch or if/else instead,  it's hard to read  🧐

2020-11-18 18:34 UTC, JulianBlohm commented on src/components/Header.js
> +      {title}
Maybe use a semantic text element for the title?

2020-11-18 18:34 UTC, JulianBlohm commented on src/components/MainButton.js
> +
If/else would be a little bit easier to read 🔎 But smart solution 🤯

2020-11-18 18:34 UTC, JulianBlohm commented on src/styles/GlobalStyles.js
> +        --primery-color: #121212;
```suggestion
        --primary-color: #121212;
```
written with "a" :)

2020-11-18 18:34 UTC, JulianBlohm commented on src/styles/GlobalStyles.js
> +        --default-heder-color: #e5e5e5;
```suggestion
        --default-header-color: #e5e5e5;
```
Now I know why it worked where you called it 😃

2020-11-18 18:34 UTC, JulianBlohm commented on src/styles/GlobalStyles.js
> +        cursor: pointer;
Important detail! 🤓

2020-11-18 19:51 UTC, Hecktors commented on src/App.js
> +  const [appState, setAppState] = useState('default')
I agree

2020-11-18 19:52 UTC, Hecktors commented on src/App.js
> +  background-color: var(--primery-color);
You got me again...

2020-11-18 19:52 UTC, Hecktors commented on src/components/Header.js
> +      ? 'var(--default-heder-color)'
😱

2020-11-18 19:54 UTC, Hecktors commented on src/components/Header.js
> +
Guess I'll stick with it

2020-11-18 19:54 UTC, Hecktors commented on src/components/Header.js
> +      {title}
Good point

2020-11-18 19:59 UTC, Hecktors commented on src/components/MainButton.js
> +
Prettier wraps the components in blackets and formats it like that. Otherwise it really would be easier to read...

2020-11-18 20:00 UTC, Hecktors commented on src/styles/GlobalStyles.js
> +        --primery-color: #121212;
No comment...

2020-11-19 14:37 UTC, marwinburesch requested changes
Good stuff, just a few small suggestions :)
very nice!
🐜

2020-11-19 14:37 UTC, marwinburesch commented on src/App.js
> +      <main></main>
I don't see the need for this `<main>`

2020-11-19 14:37 UTC, marwinburesch commented on src/App.js
> +const AppStyled = styled.div`
I'd use words like wrapper/container/grid, in combination with a word that brings them into context, here instead of `AppStyled`

2020-11-19 14:37 UTC, marwinburesch commented on src/components/Header.js
> +
I think it's a bit specific for this component, why don't you lift the logic up or combine it with existing logic higher up in your app?
I'm thinking maybe have a more complex state in `App.js` that can control several components, because the app seems to be constructed around the current song playing, where it is at etc. anyway. So why not have the text in Header be connected directly to that as well?

2020-11-19 14:37 UTC, marwinburesch commented on src/components/Header.md
> +<Header appState="pausing" />
'pausing' doesn't add up with other states of `appState` I think it's supposed to be 'paused'

2020-11-19 14:37 UTC, marwinburesch commented on src/components/Header.test.js
> +  it('shows stop button if paused, show correct ', () => {
```suggestion
  it('shows stop button if appState is paused', () => {
```
and doesn't it also render a 'stop' button?

2020-11-19 14:37 UTC, marwinburesch commented on src/components/Header.js
> +      ? 'Bailamos!!!'
BAILANDO BAILANDO!

2020-11-19 14:37 UTC, marwinburesch commented on src/components/HeaderButton.js
> +  top: 10px;
It would be so awesome if that button would always be vertically centred in the `Header` no matter the font size, mmmmh ;)

2020-11-19 16:27 UTC, Hecktors commented on src/App.js
> +      <main></main>
Its still empty but I need it for the main grid to work

2020-11-19 16:30 UTC, Hecktors commented on src/App.js
> +const AppStyled = styled.div`
Oki!

2020-11-19 16:35 UTC, Hecktors commented on src/components/Header.js
> +
I see the point. Going to change it!

2020-11-19 16:38 UTC, Hecktors commented on src/components/Header.md
> +<Header appState="pausing" />
True

2020-11-19 16:42 UTC, Hecktors commented on src/components/Header.js
> +      ? 'Bailamos!!!'
🕺💃

2020-11-19 16:43 UTC, Hecktors commented on src/components/HeaderButton.js
> +  top: 10px;
Going to think about it

2020-11-19 16:44 UTC, Hecktors commented
Thanks! Best code review ever!

2020-11-19 16:53 UTC, merged